### ISSUE TITLE
Unable to create label documents

### ISSUE THREAD

**Issue by szelenka** [kofc7186/fishfry-google-square#2]
It seems the gmail account that's viewing the spreadsheet will need write access to generate the label documents. Currently my gmail account does not have permission to write to the **ff_labels** folder here:
https://drive.google.com/drive/folders/17w2fxSktZ5AIXRlgZukKiQ9dNspBLGKj

**Comment by bobcallaway** [comment]
permissions updated. let me know if it still isn't working.
